---
- name: Install Java 17 and Maven 3.0 on Ubuntu
  hosts: app
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_facts['distribution'] in ['Ubuntu']

    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present
      when: ansible_facts['distribution'] in ['Ubuntu']

    - name: Add the Apache Maven PPA
      apt_repository:
        repo: 'ppa:andrei-pozolotin/maven3'
        state: present

    - name: Install Maven 3.0
      apt:
        name: maven
        state: present
      when: ansible_facts['distribution'] in ['Ubuntu']

    - name: Verify Java installation
      command: java -version
      register: java_version

    - name: Verify Maven installation
      command: mvn -version
      register: maven_version

  handlers:
    - name: Restart service
      service:
        name: some_service
        state: restarted



