---
- name: Install and configure Nginx as reverse proxy
  hosts: web
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: ansible_facts ['distribution'] in ['Amazon', 'Redhat']

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_facts ['distribution'] in ['Amazon', 'Redhat']

    - name: Configure Nginx as a reverse proxy
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
      notify:
        - Restart Nginx
      become: true

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
      become: true
