name: Deploy AWS EC2 Instances

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action: apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
  AWS_DEFAULT_REGION: eu-west-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Check for jq
        run: |
          if ! command -v jq &> /dev/null
          then
            echo "jq is not installed. Exiting."
            exit 1
          else
            echo "jq is installed."
          fi

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=plan.tfplan

      - name: Validate Terraform Output
        run: |
          terraform output -json > output.json
          jq empty output.json
          if [ $? -ne 0 ]; then
            echo "Invalid JSON output from Terraform. Exiting."
            exit 1
          else
            echo "Valid JSON output from Terraform."
          fi

      - name: Check for Changes
        id: changes
        run: |
          CHANGES=$(terraform show -json plan.tfplan | jq -r '.resource_changes | length')
          if [[ $CHANGES -eq 0 ]]; then
            echo "No changes detected."
            exit 0
          fi
          echo "::set-output name=changes::$CHANGES"

      - name: Terraform Apply
        if: github.event_name == 'push' || (github.event.inputs.action == 'apply' && steps.changes.outputs.changes != '0')
        run: terraform apply -auto-approve plan.tfplan

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
